class CountryData {
  static const Map<String, List<String>> countryStates = {
    'India': [
      'Andhra Pradesh',
      'Arunachal Pradesh',
      'Assam',
      'Bihar',
      'Chhattisgarh',
      'Goa',
      'Gujarat',
      'Haryana',
      'Himachal Pradesh',
      'Jharkhand',
      'Karnataka',
      'Kerala',
      'Madhya Pradesh',
      'Maharashtra',
      'Manipur',
      'Meghalaya',
      'Mizoram',
      'Nagaland',
      'Odisha',
      'Punjab',
      'Rajasthan',
      'Sikkim',
      'Tamil Nadu',
      'Telangana',
      'Tripura',
      'Uttar Pradesh',
      'Uttarakhand',
      'West Bengal',
      'Delhi',
      'Jammu and Kashmir',
      'Ladakh',
      'Puducherry',
      'Chandigarh',
    ],
    'USA': [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming',
    ],
    'UK': [
      'England',
      'Scotland',
      'Wales',
      'Northern Ireland',
    ],
    'Canada': [
      'Alberta',
      'British Columbia',
      'Manitoba',
      'New Brunswick',
      'Newfoundland and Labrador',
      'Northwest Territories',
      'Nova Scotia',
      'Nunavut',
      'Ontario',
      'Prince Edward Island',
      'Quebec',
      'Saskatchewan',
      'Yukon',
    ],
    'Australia': [
      'New South Wales',
      'Victoria',
      'Queensland',
      'Western Australia',
      'South Australia',
      'Tasmania',
      'Australian Capital Territory',
      'Northern Territory',
    ],
  };

  static const Map<String, Map<String, dynamic>> pincodeFormats = {
    'India': {
      'label': 'PIN Code',
      'placeholder': '110001',
      'maxLength': 6,
      'pattern': r'^\d{6}$',
      'errorMessage': 'Please enter a valid 6-digit PIN code',
    },
    'USA': {
      'label': 'ZIP Code',
      'placeholder': '10001',
      'maxLength': 5,
      'pattern': r'^\d{5}$',
      'errorMessage': 'Please enter a valid 5-digit ZIP code',
    },
    'UK': {
      'label': 'Postcode',
      'placeholder': 'SW1A 1AA',
      'maxLength': 8,
      'pattern': r'^[A-Z]{1,2}\d{1,2}[A-Z]?\s?\d[A-Z]{2}$',
      'errorMessage': 'Please enter a valid UK postcode',
    },
    'Canada': {
      'label': 'Postal Code',
      'placeholder': 'K1A 0B1',
      'maxLength': 7,
      'pattern': r'^[A-Z]\d[A-Z]\s?\d[A-Z]\d$',
      'errorMessage': 'Please enter a valid postal code (e.g., K1A 0B1)',
    },
    'Australia': {
      'label': 'Postcode',
      'placeholder': '2000',
      'maxLength': 4,
      'pattern': r'^\d{4}$',
      'errorMessage': 'Please enter a valid 4-digit postcode',
    },
  };

  static List<String> getStatesForCountry(String country) {
    return countryStates[country] ?? [];
  }

  static Map<String, dynamic> getPincodeFormat(String country) {
    return pincodeFormats[country] ?? pincodeFormats['India']!;
  }

  static bool validatePincode(String country, String pincode) {
    final format = getPincodeFormat(country);
    final pattern = RegExp(format['pattern'] as String, caseSensitive: false);
    return pattern.hasMatch(pincode.toUpperCase());
  }
}
